//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Effetrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga
    {
        public int IdCarga { get; set; }
        public int IdEnvio { get; set; }
        public int IdTipo_Carga { get; set; }
        public decimal Peso { get; set; }
        public int Cantidad { get; set; }
        public decimal Longitud { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Envio Envio { get; set; }
        public virtual Tipo_Carga Tipo_Carga { get; set; }
    }
}
