//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Effetrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Envio()
        {
            this.Carga = new HashSet<Carga>();
            this.Oferta = new HashSet<Oferta>();
        }
    
        public int IdEnvio { get; set; }
        public int IdUsuario { get; set; }
        public string Direccion { get; set; }
        public System.DateTime Fecha_Limite_Llegada { get; set; }
        public int Codigo_Postal { get; set; }
        public string Comentario_Envio { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public int IdDepartamento { get; set; }
        public int IdCiudad { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carga> Carga { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
    }
}
